spring:
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: scampaddress@gmail.com
    port: '587'
    password: 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Svetsyn123
    username: root
    url: jdbc:mysql://localhost:3306/scamp_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'



# THIS was old version like properties
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=Svetsyn123
#spring.datasource.url=jdbc:mysql://localhost:3306/scamp_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=scampaddress@gmail.com
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
